Loja_Pesadelo_2.5.3/config/routes.rb
Rails.application.routes.draw do
  resources :produto_no_carrinhos
  resources :carrinhos
  resources :produtos
  devise_for :users
  resources :users

  get 'carrinhos/:id/show_prods' => 'carrinhos#show_prods'
  get 'produtos/:id/buy' => 'produtos#add'
  get 'produto_no_carrinhos/:id/remove' => 'produto_no_carrinhos#remove'
  root to: "produtos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Loja_Pesadelo_2.5.3/app/models/produto.rb
class Produto < ApplicationRecord
end

Loja_Pesadelo_2.5.3/app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  load_and_authorize_resource 
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add 
    @produto = Produto.find(params[:id])
    @produto.quantidade -= 1
    @produto.save

    prod_temp = ProdutoNoCarrinho.new
    prod_temp.quantidade = 1
    prod_temp.preco_1 = @produto.preco_1
    prod_temp.preco_2 = @produto.preco_2
    prod_temp.preco_3 = @produto.preco_3
    prod_temp.nome = @produto.nome
    array = []
    current_user.carrinho.produto_no_carrinhos.each do |prod|
      array << prod
    end

    if array.empty?
      prod_new = ProdutoNoCarrinho.new
      array << prod_new
    end
    array << prod_temp
    current_user.carrinho.produto_no_carrinhos = array
    prod_temp.save
    if current_user.atleta? || current_user.admin?
      current_user.carrinho.preco_final += @produto.preco_1
    elsif current_user.associado?
      current_user.carrinho.preco_final += @produto.preco_2
    else
      current_user.carrinho.preco_final += @produto.preco_3
    end
    current_user.carrinho.save
    respond_to do |format|
      format.html { redirect_to produtos_url, notice:  'Produto comprado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:preco_1, :preco_2, :preco_3, :nome, :quantidade, :imagem)
    end
end

Loja_Pesadelo_2.5.3/app/helpers/produtos_helper.rb
module ProdutosHelper
end

Loja_Pesadelo_2.5.3/app/views/produtos/_form.html.erb
<%= form_with(model: produto, local: true) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :preco_1 %>
    <%= form.text_field :preco_1 %>
  </div>

  <div class="field">
    <%= form.label :preco_2 %>
    <%= form.text_field :preco_2 %>
  </div>

  <div class="field">
    <%= form.label :preco_3 %>
    <%= form.text_field :preco_3 %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :quantidade %>
    <%= form.number_field :quantidade %>
  </div>

  <div class="field">
    <%= form.label :imagem %>
    <%= form.text_field :imagem %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Loja_Pesadelo_2.5.3/app/views/produtos/edit.html.erb
<h1>Editing Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

Loja_Pesadelo_2.5.3/app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produtos</h1>

<table>
  <thead>
    <tr>

    <% if current_user.admin? || current_user.atleta?%>
      <th>Preco</th>
    <% end %>
    <% if current_user.admin? || current_user.associado?%>
      <th>Preco</th>
    <% end %>
    <% if current_user.admin? || (!current_user.atleta? && !current_user.associado?) %>
      <th>Preco</th>
    <% end %>
      <th>Nome</th>
      <th>Quantidade</th>
      <th>Imagem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <% if current_user.admin? || current_user.atleta?%>
          <td><%= produto.preco_1 %></td>
        <% end %>
        <% if current_user.admin? || current_user.associado?%>
          <td><%= produto.preco_2 %></td>
        <% end %>
        <% if current_user.admin? || (!current_user.atleta? && !current_user.associado?) %>
          <td><%= produto.preco_3 %></td>
        <% end %>
          <td><%= produto.nome %></td>
          <td><%= produto.quantidade %></td>
          <td><%= produto.imagem %></td>
          <td><%= link_to 'Adicionar ao Carrinho', produto_path(produto) + '/buy' %></td> 
          <td><%= link_to 'Show', produto %></td>
          <% if current_user.admin? %>
            <td><%= link_to 'Edit', edit_produto_path(produto) %></td>
            <td><%= link_to 'Destroy', produto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.admin? %>
  <%= link_to 'New Produto', new_produto_path %>
<% end %>

Loja_Pesadelo_2.5.3/app/views/produtos/new.html.erb
<h1>New Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Back', produtos_path %>

Loja_Pesadelo_2.5.3/app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>
<% if current_user.admin? || current_user.atleta? %>
<p>
  <strong>Preco:</strong>
  <%= @produto.preco_1 %>
</p>
<% end %>
<% if current_user.admin? || current_user.associado? %>
<p>
  <strong>Preco:</strong>
  <%= @produto.preco_2 %>
</p>
<% end %>
<% if current_user.admin? || (!current_user.atleta? && !current_user.associado?) %>
<p>
  <strong>Preco 3:</strong>
  <%= @produto.preco_3 %>
</p>
<% end %>
<p>
  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @produto.quantidade %>
</p>

<p>
  <strong>Imagem:</strong>
  <%= @produto.imagem %>
</p>
<% if current_user.admin? %>
  <%= link_to 'Edit', edit_produto_path(@produto) %> |
  <%= link_to 'Back', produtos_path %>
<% end %>
  <%= link_to 'Adicionar ao Carrinho', produto_path(@produto) + '/buy' %>