Loja_Pesadelo_2.5.3/config/routes.rb
Rails.application.routes.draw do
  resources :produto_no_carrinhos
  resources :carrinhos
  resources :produtos
  devise_for :users
  resources :users

  get 'carrinhos/:id/show_prods' => 'carrinhos#show_prods'
  get 'produtos/:id/buy' => 'produtos#add'
  get 'produto_no_carrinhos/:id/remove' => 'produto_no_carrinhos#remove'
  root to: "produtos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Loja_Pesadelo_2.5.3/app/models/produto_no_carrinho.rb
class ProdutoNoCarrinho < ApplicationRecord
	belongs_to :carrinho
end

Loja_Pesadelo_2.5.3/app/controllers/produto_no_carrinhos_controller.rb
class ProdutoNoCarrinhosController < ApplicationController
  before_action :set_produto_no_carrinho, only: [:show, :edit, :update, :destroy]

  # GET /produto_no_carrinhos
  # GET /produto_no_carrinhos.json
  def index
    @produto_no_carrinhos = ProdutoNoCarrinho.all
  end

  # GET /produto_no_carrinhos/1
  # GET /produto_no_carrinhos/1.json
  def show
  end

  # GET /produto_no_carrinhos/new
  def new
    @produto_no_carrinho = ProdutoNoCarrinho.new
  end

  # GET /produto_no_carrinhos/1/edit
  def edit
  end

  # POST /produto_no_carrinhos
  # POST /produto_no_carrinhos.json
  def create
    @produto_no_carrinho = ProdutoNoCarrinho.new(produto_no_carrinho_params)

    respond_to do |format|
      if @produto_no_carrinho.save
        format.html { redirect_to @produto_no_carrinho, notice: 'Produto no carrinho was successfully created.' }
        format.json { render :show, status: :created, location: @produto_no_carrinho }
      else
        format.html { render :new }
        format.json { render json: @produto_no_carrinho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produto_no_carrinhos/1
  # PATCH/PUT /produto_no_carrinhos/1.json
  def update
    respond_to do |format|
      if @produto_no_carrinho.update(produto_no_carrinho_params)
        format.html { redirect_to @produto_no_carrinho, notice: 'Produto no carrinho was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto_no_carrinho }
      else
        format.html { render :edit }
        format.json { render json: @produto_no_carrinho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produto_no_carrinhos/1
  # DELETE /produto_no_carrinhos/1.json
  def destroy
    @produto_no_carrinho.destroy
    respond_to do |format|
      format.html { redirect_to produto_no_carrinhos_url, notice: 'Produto no carrinho was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove
    @produto_no_carrinho = ProdutoNoCarrinho.find(params[:id])
    array = []
    current_user.carrinho.produto_no_carrinhos.each do |prod|
      if prod.id != @produto_no_carrinho.id
        array << prod
      end
    end
    if current_user.atleta? || current_user.admin?
      current_user.carrinho.preco_final -= @produto_no_carrinho.preco_1
    elsif current_user.associado?
      current_user.carrinho.preco_final -= @produto_no_carrinho.preco_2
    else
      current_user.carrinho.preco_final -= @produto_no_carrinho.preco_3
    end
    current_user.carrinho.save

    @produtos = Produto.all
    @produtos.each do |produto|
      if produto.nome == @produto_no_carrinho.nome
        produto.quantidade += 1
        produto.save
        break
      end
    end
    @produto_no_carrinho.destroy
    respond_to do |format|
      format.html { redirect_to carrinho_path(current_user.carrinho) + '/show_prods'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto_no_carrinho
      @produto_no_carrinho = ProdutoNoCarrinho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_no_carrinho_params
      params.require(:produto_no_carrinho).permit(:nome, :quantidade, :preco_1, :preco_2, :preco_3)
    end
end

Loja_Pesadelo_2.5.3/app/helpers/produto_no_carrinhos_helper.rb
module ProdutoNoCarrinhosHelper
end

Loja_Pesadelo_2.5.3/app/views/produto_no_carrinhos/_form.html.erb
<%= form_with(model: produto_no_carrinho, local: true) do |form| %>
  <% if produto_no_carrinho.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto_no_carrinho.errors.count, "error") %> prohibited this produto_no_carrinho from being saved:</h2>

      <ul>
      <% produto_no_carrinho.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :quantidade %>
    <%= form.number_field :quantidade %>
  </div>

  <div class="field">
    <%= form.label :preco_1 %>
    <%= form.text_field :preco_1 %>
  </div>

  <div class="field">
    <%= form.label :preco_2 %>
    <%= form.text_field :preco_2 %>
  </div>

  <div class="field">
    <%= form.label :preco_3 %>
    <%= form.text_field :preco_3 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Loja_Pesadelo_2.5.3/app/views/produto_no_carrinhos/edit.html.erb
<h1>Editing Produto No Carrinho</h1>

<%= render 'form', produto_no_carrinho: @produto_no_carrinho %>

<%= link_to 'Show', @produto_no_carrinho %> |
<%= link_to 'Back', produto_no_carrinhos_path %>

Loja_Pesadelo_2.5.3/app/views/produto_no_carrinhos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produto No Carrinhos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Quantidade</th>
      <th>Preco 1</th>
      <th>Preco 2</th>
      <th>Preco 3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produto_no_carrinhos.each do |produto_no_carrinho| %>
      <tr>
        <td><%= produto_no_carrinho.nome %></td>
        <td><%= produto_no_carrinho.quantidade %></td>
        <td><%= produto_no_carrinho.preco_1 %></td>
        <td><%= produto_no_carrinho.preco_2 %></td>
        <td><%= produto_no_carrinho.preco_3 %></td>
        <td><%= link_to 'Show', produto_no_carrinho %></td>
        <td><%= link_to 'Edit', edit_produto_no_carrinho_path(produto_no_carrinho) %></td>
        <td><%= link_to 'Destroy', produto_no_carrinho, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produto No Carrinho', new_produto_no_carrinho_path %>

Loja_Pesadelo_2.5.3/app/views/produto_no_carrinhos/new.html.erb
<h1>New Produto No Carrinho</h1>

<%= render 'form', produto_no_carrinho: @produto_no_carrinho %>

<%= link_to 'Back', produto_no_carrinhos_path %>

Loja_Pesadelo_2.5.3/app/views/produto_no_carrinhos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @produto_no_carrinho.nome %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @produto_no_carrinho.quantidade %>
</p>

<p>
  <strong>Preco 1:</strong>
  <%= @produto_no_carrinho.preco_1 %>
</p>

<p>
  <strong>Preco 2:</strong>
  <%= @produto_no_carrinho.preco_2 %>
</p>

<p>
  <strong>Preco 3:</strong>
  <%= @produto_no_carrinho.preco_3 %>
</p>

<%= link_to 'Edit', edit_produto_no_carrinho_path(@produto_no_carrinho) %> |
<%= link_to 'Back', produto_no_carrinhos_path %>