Loja_Pesadelo_2.5.3/config/routes.rb
Rails.application.routes.draw do
  resources :produto_no_carrinhos
  resources :carrinhos
  resources :produtos
  devise_for :users
  resources :users

  get 'carrinhos/:id/show_prods' => 'carrinhos#show_prods'
  get 'produtos/:id/buy' => 'produtos#add'
  get 'produto_no_carrinhos/:id/remove' => 'produto_no_carrinhos#remove'
  root to: "produtos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Loja_Pesadelo_2.5.3/app/models/carrinho.rb
class Carrinho < ApplicationRecord
  belongs_to :user
  has_many :produto_no_carrinhos
end

Loja_Pesadelo_2.5.3/app/controllers/carrinhos_controller.rb
class CarrinhosController < ApplicationController
  load_and_authorize_resource
  before_action :set_carrinho, only: [:show, :edit, :update, :destroy]

  # GET /carrinhos
  # GET /carrinhos.json
  def index
    @carrinhos = Carrinho.all
  end

  # GET /carrinhos/1
  # GET /carrinhos/1.json
  def show
  end

  # GET /carrinhos/new
  def new
    @carrinho = Carrinho.new
    current_user.carrinho = @carrinho
    current_user.carrinho.preco_final = 0.0
  end

  # GET /carrinhos/1/edit
  def edit
  end

  # POST /carrinhos
  # POST /carrinhos.json
  def create
    @carrinho = Carrinho.new(carrinho_params)

    respond_to do |format|
      if @carrinho.save
        format.html { redirect_to carrinho_path(current_user.carrinho) + '/show_prods', notice: 'Carrinho was successfully created.' }
        format.json { render :show, status: :created, location: @carrinho }
      else
        format.html { render :new }
        format.json { render json: @carrinho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carrinhos/1
  # PATCH/PUT /carrinhos/1.json
  def update
    respond_to do |format|
      if @carrinho.update(carrinho_params)
        format.html { redirect_to carrinho_path(current_user.carrinho) + '/show_prods', notice: 'Carrinho was successfully updated.' }
        format.json { render :show, status: :ok, location: @carrinho }
      else
        format.html { render :edit }
        format.json { render json: @carrinho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carrinhos/1
  # DELETE /carrinhos/1.json
  def destroy
    @carrinho.destroy
    respond_to do |format|
      format.html { redirect_to carrinhos_url, notice: 'Carrinho was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def show_prods
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrinho
      @carrinho = Carrinho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carrinho_params
      params.require(:carrinho).permit(:preco_final, :user_id)
    end
end

Loja_Pesadelo_2.5.3/app/helpers/carrinhos_helper.rb
module CarrinhosHelper
end

Loja_Pesadelo_2.5.3/app/views/carrinhos/_form.html.erb
<%= form_with(model: carrinho, local: true) do |form| %>
  <% if carrinho.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carrinho.errors.count, "error") %> prohibited this carrinho from being saved:</h2>

      <ul>
      <% carrinho.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :preco_final %>
    <%= form.text_field :preco_final %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Loja_Pesadelo_2.5.3/app/views/carrinhos/edit.html.erb
<h1>Editing Carrinho</h1>

<%= render 'form', carrinho: @carrinho %>

<%= link_to 'Show', @carrinho %> |
<%= link_to 'Back', carrinhos_path %>

Loja_Pesadelo_2.5.3/app/views/carrinhos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carrinhos</h1>

<table>
  <thead>
    <tr>
      <th>Preco final</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carrinhos.each do |carrinho| %>
      <tr>
        <td><%= carrinho.preco_final %></td>
        <td><%= carrinho.user %></td>
        <td><%= link_to 'Show', carrinho %></td>
        <td><%= link_to 'Edit', edit_carrinho_path(carrinho) %></td>
        <td><%= link_to 'Destroy', carrinho, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carrinho', new_carrinho_path %>

Loja_Pesadelo_2.5.3/app/views/carrinhos/new.html.erb
<h1>New Carrinho</h1>

<%= render 'form', carrinho: @carrinho %>

<%= link_to 'Back', carrinhos_path %>

Loja_Pesadelo_2.5.3/app/views/carrinhos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Preco final:</strong>
  <%= @carrinho.preco_final %>
</p>

<p>
  <strong>User:</strong>
  <%= @carrinho.user %>
</p>

<%= link_to 'Edit', edit_carrinho_path(@carrinho) %> |
<%= link_to 'Back', carrinhos_path %>

Loja_Pesadelo_2.5.3/app/views/carrinhos/show_prods.html.erb
<h1>Carrinho</h1>
<h2> <%= current_user.carrinho.preco_final %></h2>
<table>
  <thead>
    <tr>

    <% if current_user.admin? || current_user.atleta?%>
      <th>Preco</th>
    <% end %>
    <% if current_user.admin? || current_user.associado?%>
      <th>Preco</th>
    <% end %>
    <% if current_user.admin? || (!current_user.atleta? && !current_user.associado?) %>
      <th>Preco</th>
    <% end %>
      <th>Nome</th>
      <th>Quantidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.carrinho.produto_no_carrinhos.each do |produto_no_carrinho| %>
      <tr>
        <% if produto_no_carrinho.nome != nil %>
          <% if current_user.admin? || current_user.atleta?%>
            <td><%= produto_no_carrinho.preco_1 %></td>
          <% end %>
          <% if current_user.admin? || current_user.associado?%>
            <td><%= produto_no_carrinho.preco_2 %></td>
          <% end %>
          <% if current_user.admin? || (!current_user.atleta? && !current_user.associado?) %>
            <td><%= produto_no_carrinho.preco_3 %></td>
          <% end %>
            <td><%= produto_no_carrinho.nome %></td>
            <td><%= produto_no_carrinho.quantidade %></td>
            <td><%= produto_no_carrinho.id %></td>
            <td><%= link_to 'Remove', produto_no_carrinho_path(produto_no_carrinho) + '/remove' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>