Loja_Pesadelo_2.5.3/config/routes.rb
Rails.application.routes.draw do
  resources :produto_no_carrinhos
  resources :carrinhos
  resources :produtos
  devise_for :users
  resources :users

  get 'carrinhos/:id/show_prods' => 'carrinhos#show_prods'
  get 'produtos/:id/buy' => 'produtos#add'
  get 'produto_no_carrinhos/:id/remove' => 'produto_no_carrinhos#remove'
  root to: "produtos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Loja_Pesadelo_2.5.3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    Logado como: <strong><%= current_user.name %></strong>.
    <% if current_user.carrinho != nil %>
    <%= link_to 'Carrinho', carrinho_path(current_user.carrinho) + '/show_prods', :class => 'navbar-link' %> |
    <% else %>
    <%= link_to 'Gerar Carrinho', new_carrinho_path, :class => 'navbar-link' %> |
    <% end %>
    <%= link_to 'Editar Perfil', edit_user_path(current_user), :class => 'navbar-link' %> |
    <%= link_to 'Editar Login/Senha', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
  </p>
  
  <head>
    <title>Site</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

  <p class="navbar-text pull-right">
    <%= link_to 'Produtos', 'http://localhost:3000/produtos', :class => 'navbar-link' %> 
  </p>
</html>